name: quora
channels:
  - defaults
dependencies:
  - python==3.8.10
  - pip
  - pip:
    - numpy==1.22.1
    - lightgbm==3.3.2
    - pandas==1.4.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - torch==1.10.1
    - xgboost==1.5.2